name: default

on:
  push:
    branches: []
  pull_request:
    branches: []

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      
      - name: Configure
        run: cmake -B build -S .
        
      - name: Build
        run: cmake --build build --clean-first -j12

      - name: Run
        run: ./build/test/testgol
